### ISSUE TITLE
gem compatibility issue with rails

### ISSUE THREAD

**Issue by jalenlinden** [swagger-rb/swagger-rb#2]
Fetching gem metadata from https://rubygems.org/........
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "mime-types":
  In Gemfile:
    swagger-core (>= 0) ruby depends on
      mime-types (~> 2.0) ruby

```
rails (= 4.1.1) ruby depends on
  actionmailer (= 4.1.1) ruby depends on
    mail (~> 2.5.4) ruby depends on
      mime-types (1.25.1)
```

Thoughts?

**Comment by maxlinc** [comment]
Thanks for letting me know. I planned to keep minimize dependencies to avoid issues like this, but for the first iteration I prioritized ease of development over minimal dependencies. So I'll try to relax or remove the mime-times dependency.

Could you share some details on how you plan to use Swagger + Rails? If I know how it's used it'll be easier for me to add tests to ensure compatibility. I don't know of many projects that use Swagger + Rails and the ones I do know about (like [grape-swagger-rails](https://github.com/BrandyMint/grape-swagger-rails) or [swagger-docs](https://github.com/richhollis/swagger-docs)) don't currently depend on swagger-core.

**Comment by jalenlinden** [comment]
We're using Swagger to document our Rails API. Specifically, we're manually
crafting our documentation using Swagger Editor and hope to use your gem to
convert YAML to JSON format.

**Comment by maxlinc** [comment]
It looks like this was problematic for several other projects and has been fixed upstream: https://github.com/mikel/mail/issues/641 and https://github.com/rails/rails/pull/15493.

It looks like it will work fine with Rails 4.1.10 or later. Is anything preventing you from doing a bundle update?

**Comment by jalenlinden** [comment]
Ah, great. Didn't realize this was project was that far behind. It's
currently on 4.1.1. Thanks!

**Comment by maxlinc** [comment]
In addition to the rails upgrade, mime-types version is relaxed with #18
