### ISSUE TITLE
Allow $ref for parameters

### ISSUE THREAD

**Issue by jharmn** [swagger-rb/swagger-rb#6]
From: https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#path-item-object

> A list of parameters that are applicable for all the operations described under this path. These parameters can be overridden at the operation level, but cannot be removed there. The list MUST NOT include duplicated parameters. A unique parameter is defined by a combination of a name and location. The list can use the Reference Object to link to parameters that are defined at the Swagger Object's parameters. There can be one "body" parameter at most.

In other words, this should be allowed:

``` yaml
      parameters:
        - $ref: '#/parameters/myParam'
```

This would be handled much like schema resolves `$ref` (although arguably simpler as it should be one-level resolution).

**Comment by maxlinc** [comment]
Should be fixed by 8a5dce4f3386d48dd8605d7fbb361559c5cb8195
